site_name: XenoAI Docs
nav:
    - Home: index.md
    - API Usage: api_usage.md
    - API Endpoints: api_endpoints.md
    - Requesting API Key: request_api_key.md
    - Rate Limits: rate_limits.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - admonition
  - pymdownx.details
  - pymdownx.superfences